site_name: DevSecOps Platform for data pipelines and ML workflows
site_description: Comprehensive DevSecOps platform for data engineering and AI/ML workloads
site_author: DevSecOps Team
site_url: https://Exemplify777.github.io/aws-cdk-devsecops-platform

repo_name: Exemplify777/aws-cdk-devsecops-platform
repo_url: https://github.com/Exemplify777/aws-cdk-devsecops-platform
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mermaid2:
      arguments:
        theme: base
        themeVariables:
          primaryColor: '#1976d2'
          primaryTextColor: '#ffffff'
          primaryBorderColor: '#0d47a1'
          lineColor: '#424242'
          sectionBkColor: '#e3f2fd'
          altSectionBkColor: '#bbdefb'
          gridColor: '#9e9e9e'
          secondaryColor: '#ff9800'
          tertiaryColor: '#4caf50'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - Architecture:
    - Overview: architecture/overview.md
    - Infrastructure: architecture/infrastructure.md
    - Security: architecture/security.md
    - Data Pipeline: architecture/data-pipeline.md
    - Monitoring: architecture/monitoring.md
    - AI Tools: architecture/ai-tools.md
  - User Guide:
    - CLI Reference: user-guide/cli.md
    - Project Templates: user-guide/templates.md
    - Web Portal: user-guide/portal.md
    - Best Practices: user-guide/best-practices.md
  - Tutorials:
    - First Data Pipeline: tutorials/first-pipeline.md
    - ML Workflow: tutorials/ml-workflow.md
    - Streaming Analytics: tutorials/streaming.md
    - Custom AI Tools: tutorials/ai-tools.md
  - Security:
    - Security Overview: security/overview.md
    - Security Scanning: security/scanning.md
    - Compliance: security/compliance.md
    - Implementation: security/implementation.md
  - Operations:
    - Deployment Guide: operations/deployment.md
    - Monitoring & Alerting: operations/monitoring.md
    - CI/CD: operations/cicd.md
    - Troubleshooting: operations/troubleshooting.md
  - Developer Guide:
    - Development Setup: developer-guide/setup.md
    - Extending Platform: developer-guide/extending.md
    - Contributing: developer-guide/contributing.md
    - Testing: developer-guide/testing.md
  - API Reference:
    - Overview: api/index.md
    - CLI API: api/cli.md
    - Python API: api/python.md
    - REST API: api/rest.md
  - Compliance:
    - SOC 2: compliance/soc2.md
    - ISO 27001: compliance/iso27001.md
    - GDPR: compliance/gdpr.md
    - Audit Reports: compliance/audit-reports.md
  - FAQ: faq.md
  - Changelog: changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Exemplify777/aws-cdk-devsecops-platform
    - icon: fontawesome/brands/slack
      link: https://Exemplify777.slack.com/channels/devsecops-platform
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
